### ISSUE TITLE
Query / feature request

### ISSUE THREAD

**Issue by gidzr** [stephenc222/mysql_vss#1]
Hi Stephen

Really excited to see this project. I can't wait to test it and see how it develops.

To clarify, is a 768-dimensional embedding compatible with chromadb - from my understanding it is.. but wanted to double check if there is a specific feature-extraction LLM you used as a basis for building and testing this library?

When creating a new table for vectors using this library, is that table suitable for additional non-vector columns so it's possible to have (amongst others) primary key, filepath of source document, shortname, createdDate, etc?

How well does such a table scale? If I have 100 rows vs 10,000 rows, am I going to see reasonably managable search times compared with other databases like duckdb, pinecone, etc?

Not sure what the full implications are by: "The Annoy Index loads once and requires a manual update for new embeddings". Is there a separate text file that provides a rosetta stone to the Annoy library and it requires re-writing whenever a new vector row is added to the mysql table? I think this is related to the other issue "Dynamic Index Reloading: Enable index updates without restarting the service.". Is it therefore correct to say that whenever a new embedding is added to the mysql vector table, that the Annoy Index needs to be re-written, then mysql service needs to be restarted?

Feature request: is it able to work as a plugin for mariadb, and can you eventually make it compatible with mariadb?

Much appreciated.

**Comment by stephenc222** [comment]
Hi @gidzr . Happy to hear about your interest in mysql_vss!

To answer your questions:

Essentially - you probably wouldn't use this plugin with ChromaDB to be frank. ChromaDB would be useful for known larger scale vector embedding storage needs, since the AnnoyService (the main entity guarding access to the Annoy Index) is allocated from mysql server heap memory. I suppose this could be addressed, but still limited by the amount of RAM offered by the host machine running the mysql server. Or a greater refactor to talk to a wholly different machine that creates and manages the Annoy Index. My initial thought with writing this plugin was that it would be useful for low to medium scale, content-heavy mysql databases powering wordpress sites, for example.

Yes - you can absolutely have non-vector columns in the "embedding" table.

For scaling - essentially, it scales as well as the AnnoyIndex scales within the constraints of how much heap memory the Annoy Index can have from the main MySQL server heap. Which means that generally, time complexity is sub-linear (which was the goal) albeit at increased space complexity. Considering the experimental nature of this plugin, I would venture to say that time and space complexity (currently) is probably better managed by the more established non-native vector storage solutions.

What I meant by "The Annoy Index loads once and requires a manual update for new embeddings" is that to reload the Annoy Index requires a restart of the MySQL server. I hadn't yet implemented a way to reload / update the AnnoyIndex, which is an important future part of this plugin without a doubt. So you are correct.

I haven't tested it with mariadb. I'm open to hearing about whether or not it is!
